### PR TITLE
Add comment-style highlighting to POD.

### LINKED ISSUE #24: Highlight Pod the same as comments
Currently, blocks of Pod are highlighted as code, rather than comments. Consider the following example, which I would expect to be uniformly coloured the same as a comment:

```
=begin pod

=head1 This is a head.

Note: For testing purposes, "here is a string".

=end pod
```

Being able to distinguish Pod from actual code would help orientation in code documented with Pod.

### PR DESCRIPTION
**Pull request by tmtvl**
Fixes #24.

### CODE REVIEW

**Comment by matiaslina** [comment]
Cool @tmtvl ! I will check this out after work.

**Comment by Altai-man** [comment]
Pod also supports inlined code which is sometimes used to demonstrate code samples and such.

I wonder if we can make it recursive like that.

**Comment by tmtvl** [comment]
@Altai-man that shouldn't be too difficult to implement if code blocks have clear delimiters. I'll have a look at the POD reference in the docs.

**Comment by tmtvl** [comment]
> A code block may be implicitly specified as one or more lines of text, each of which starts with a whitespace character. The implicit code block is then terminated by a blank line.

Any idea what that says about lines that don't start with whitespace yet aren't separated from the block by a blank line?

**Comment by Altai-man** [comment]
>Any idea what that says about lines that don't start with whitespace yet aren't separated from the block by a blank line?

Can you provide an example, please?

**Comment by Altai-man** [comment]
Sorry, accidentally closed by my horrible fingers. :(

**Comment by tmtvl** [comment]
Well, the docs give an example where it goes...

```Raku
This ordinary paragraph introduces a code block:
 
    my $name = 'John Doe';
    say $name;
```

And before that it mentions that...

> A code block may be implicitly specified as one or more lines of text, each of which starts with a whitespace character.

However, it also says...

> The implicit code block is then terminated by a blank line.

So I was wondering how to handle something like...

```Raku
regular pod text

    say "this is an implicit code block";
say "this may be part of the implicit code block or may be regular pod text?";
    say "this is definitely still code";

and this is definitely pod text.```

Making the middle line either highlighted as comment or as code would make sense, but someone less grumpy than me ought to make the call.

**Comment by matiaslina** [comment]
Seems like *reducing* the indentation ends the code block. Here is a roast test for implicit code blocks https://github.com/Raku/roast/blob/master/S26-documentation/04-code.t#L65-L86 (there are 3 code blocks there).

As for your example, there's only one code block. The third `say` it's part of the paragraph since it doesn't have a newline between the paragraph and the code.

```raku
=begin pod
regular pod text

    say "this is an implicit code block";
say "this may be part of the implicit code block or may be regular pod text?";
    say "this is definitely still code";

and this is definitely pod text.
=end pod

.say for $=pod[0];
```

```
% raku /tmp/pod.raku 
Pod::Block::Named{:name("pod")}
  Pod::Block::Para
    regular pod text
  Pod::Block::Code
    say "this is an implicit code block";
  Pod::Block::Para
    say "this may be part of the implicit code block or may be regular pod text?"; say "this is definitely still code";
  Pod::Block::Para
    and this is definitely pod text.
```

**Comment by tmtvl** [comment]
I didn't think to check roast, good call, @matiaslina!

**Comment by matiaslina** [comment]
Keep in mind @tmtvl that the `    say "this is definitely still code";` it's not a code block because it's part of the paragraph. I'd consider a code block until it finds a blank line or a line don't start with a whitespace

**Comment by tmtvl** [comment]
Okay I think this is good to go now, although I haven't compared the highlighting results to roast outliers.

**Comment by Altai-man** [comment]
@tmtvl we probably can merge this and then just open a ticket for any missed cases, won't hurt the functionality already here.

**Pull request merged**
