### PR TITLE
add: QUIT phase word in font-lock

### PR DESCRIPTION
**Pull request by Lenin1917**
this

### CODE REVIEW

**Comment by Altai-man** [comment]
Hey! Looks wise enough. However, I see that `CLOSE` is also missing. Also `DOC`.
Can you please ensure this list is complete referring to https://docs.raku.org/language/phasers ?

**Comment by Altai-man** [comment]
Oops, something bad happened to the PR...
If you don't want to have a merge commit in this branch, do a `git checkout master; git pull origin master; git checkout $my-new-feature-branch; git rebase master` and it will try to re-apply your commits on top of the latest master.

**Comment by Lenin1917** [comment]
Oh this magit)))) Sorry, I was try to interactive rebase, but.... anyway use force push(

**Comment by Altai-man** [comment]
No problem, it's safe enough when doing branches. Checking against docs I see there is no START phaser. At the very least, it seems to be NYI:

```
> TEMP {}
Nil
> CHECK {}
Nil
> START {}
===SORRY!=== Error while compiling:
Undeclared name:
    START used at line 1

>
```

I have an impression START should not be listed as one, can you please remove it as well?

**Comment by Lenin1917** [comment]
oh, name of branch path instead of patch..

**Comment by Altai-man** [comment]
Nice, thanks for your contribution!

**Comment by jnthn** [comment]
> Checking against docs I see there is no START phaser. At the very least, it seems to be NYI:

If memory serves me correctly, it's what `once` was called the better part of a decade ago, so it's more a case of No Longer Implemented. ;-)

**Pull request merged**
